apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: prom-metrics-latency
  labels:
    service: prom
    feature: metrics
    slo_name: latency
spec:
  description: 99.99% of Prometheus requests return in less than 250ms
  backend: prometheus
  method: distribution_cut
  exporters:
  - prometheus
  service_level_indicator:
    expression: http_request_duration_seconds_bucket{handler="/metrics", code=~"2.."}
    threshold_bucket: 0.25 # in seconds, corresponds to the `le` (less than) PromQL label
