name: test

on:
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: ['x64']
        python-version: ['3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v0
      - uses: actions/setup-python@v0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}  

      - name: Install dependencies
        run: make install

      - name: Run lint test
        run: make lint

  unit:
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: ['x64']
        python-version: ['3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v0
      - uses: actions/setup-python@v0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: make install

      - name: Run unittests
        run: make unit
        env:
          MIN_VALID_EVENTS: "10"
          GOOGLE_APPLICATION_CREDENTIALS: tests/unit/fixtures/fake_credentials.json

      - name: Run coverage report
        run: make coverage

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v0
      - uses: docker-practice/actions-setup-docker@v0
      - name: Build Docker image
        run: make docker_build
      - name: Run Docker tests
        run: make docker_test
